### ISSUE TITLE
Planning Your SGO Deployment Guide/Checklist

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1074]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Have a document detailing how one might consider deploying Sensu Go and considerations before deploying a cluster.

## Current Behavior
No doc for this.

## Possible Solution
Write it.

**Comment by apaskulin** [comment]
@asachs01 To create a Google Doc to keep track of scope for this issue

**Comment by apaskulin** [comment]
Considerations:

- Should you set up a cluster?
- Do you need SSL?

**Comment by cwjohnston** [comment]
[Google Doc here](https://docs.google.com/document/d/1X1sdO7herV1wzVoFmr7kz7qK_Ov1VClNZp55TSk__14/)

**Comment by apaskulin** [comment]
@Blue0ctober Here's the working outline that @cwjohnston and I put together: https://docs.google.com/document/d/1SZgTjLz4eT0iNmZC_G4514tB-WgHNrJmTzpvkBnib88/edit
