### ISSUE TITLE
Epic: API examples

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1452]
Page: API docs

To do:
Test and add examples for the following endpoints

- [x] /assets POST
- [x] /assets/:asset (PUT)
- [x] /assets/:asset (DELETE)
- [x] /authproviders (GET)
- [x] /authproviders/:name (GET)
- [x] /authproviders/:name (PUT)
- [x] /clusterroles (POST)
- [x] /clusterroles/:clusterrole (PUT)
- [x] /entities (POST)
- [ ] /entities/:entity (POST)
- [x] /entities/:entity (PUT)
- [x] /events/:entity/:check (GET)
- [x] /etcd-replicators (POST)
- [x] /filters (POST)
- [x] /filters/:filter (PUT)
- [x] /handlers (POST
- [x] /handlers/:handler (PUT)
- [x] /hooks (POST)
- [x] /hooks/:hook (PUT)
- [x] /license (GET)
- [x] /license (PUT)
- [x] /license (DELETE)
- [x] /mutators (POST)
- [x] /mutators/:mutator (PUT)
- [x] /namespaces (POST)
- [x] /namespaces/:namespace (PUT)
- [x] /rolebindings (POST)
- [x] /rolebindings/:rolebinding (PUT)
- [x] /roles (POST)
- [x] /roles/:role (PUT)
- [x] /silenced (POST)
- [x] /silenced/:silenced (PUT)

**Comment by hillaryfraley** [comment]
Next task: Update this list based on current state of docs.

**Comment by hillaryfraley** [comment]
I updated the list to reflect the current state of the API docs as of 5.16.
