### ISSUE TITLE
Generate Sensu Enterprise 3.0 documentation

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#452]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)

## Expected Behavior

Docs should cover all released versions of Sensu Enterprise

## Current Behavior

Release of Sensu Enterprise 3.0 is imminent and docs aren’t yet available.

## Possible Solution

Duplicate 2.8 docs and update them with changes for 3.0

## Context

Known changes in 3.0 include:

- [x] Built on Sensu Core 1.4.2
- [x] Breaking changes to OpsGenie integration (see #457)
- [x] Breaking change to Java package dependency (see #451)
- [x] API-only mode #469 

## To do
- [x] Generate 3.0 docs #453 
- [x] Update changelog #467
- [ ] Promote 3.0 as the latest release

@amdprophet @portertech @afstanton are you aware of any other features needing documentation updates?

**Comment by amdprophet** [comment]
Those look like the only documentation updates needed.
