### ISSUE TITLE
Epic: Sensu Go API docs

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#580]
This is a tracking ticket for all planned docs within the API section. Notes below should be moved to individual tickets once created.

- [godoc](https://godoc.org/github.com/sensu/sensu-go/backend/apid)
- [source](https://github.com/sensu/sensu-go/tree/master/backend/apid/routers), ex: [checks](https://github.com/sensu/sensu-go/blob/master/backend/apid/routers/routers.go#L138-L145)
- https://github.com/sensu/sensu-go/pull/198

To do:

- [x] Create an API docs landing page
- [x] Research API doc generation tools for Go
  - https://goswagger.io/
  - https://swaggo.github.io/swaggo.io/
- [x] Document limit for data size returned
- [x] Document authentication process

Source:

- Endpoints: https://github.com/sensu/sensu-go/tree/master/backend/apid/routers
- Response codes: https://github.com/sensu/sensu-go/tree/master/backend/apid/actions
- Types: https://github.com/sensu/sensu-go/blob/master/api/core/v2/asset.pb.go
  - API types don't include the top-level `type` and `spec` scopes
  - /api/core/v2/namespaces/default/checks/my-check
- Routers: https://github.com/sensu/sensu-go/blob/master/backend/apid/apid.go

To write:
- [x] Overview page
- [x] Assets
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
- [x] Checks
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put (needs example)
   - [x] Delete 
   - [x] Post id/execute Queue adhoc check request
   - [x] Put id/hooks/type
   - [x] Delete id/hooks/type/hook/hookid
- [x] Entities
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Filters
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Events
  - [x] Get all
  - [x] Get by entity /entity-name
  - [x] Get /entity-name/check-name
  - [x] Delete /entity-name/check-name
  - [x] Put /entity-name/check-name
  - [x] Post
- [x] Handlers
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Hooks
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Mutators
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Namespaces
   - [x] Get all
   - ~~[ ] Get~~ This only returns the namespace name used in the URL.
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Roles
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Silenced
   - [x] Get all
   - [x] Get
   - [x] Get subscriptions/{subscription}
   - [x] Get check/checkid
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Users
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Put {id}/{subresource:password}
   - [x] Put /{id}/{subresource:groups}/{group}
   - [x] Put {id}/{subresource:reinstate}
   - [x] Delete 
   - [x] Delete {id}/{subresource:groups}
   - [x] Delete {id}/{subresource:groups}/{group}
- ~~[ ] Extensions~~
   - ~~[ ] Get all~~
   - ~~[ ] Get~~
   - ~~[ ] Post~~
   - ~~[ ] Put~~
   - ~~[ ] Delete~~ 
- [x] Cluster
  - [x] Get cluster/members
  - [x] Post cluster/members
  - [x] Delete cluster/members/{id}
  - [x] Put cluster/members/{id}
- [x] Cluster roles
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Role bindings
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Cluster role bindings
   - [x] Get all
   - [x] Get
   - [x] Post
   - [x] Put
   - [x] Delete 
- [x] Health
  - [x] Get `{"Alarms":null,"ClusterHealth":[{"MemberID":9882886658148554927,"Name":"default","Err":"","Healthy":true}]}`
- [x] Auth

Authentication process:
```
$ cat ~/.config/sensu/sensuctl/cluster|grep access_token
  "access_token": "xxx",

$ curl http://127.0.0.1:8080/rbac/users \
> -H "Authorization: Bearer xxx"
[{"username":"admin","roles":["admin"],"disabled":false},{"username":"agent","roles":["agent"],"disabled":false},{"username":"sensu","roles":["read-only"],"disabled":false}]
```

**Comment by jspaleta** [comment]
hey,
So sensu-backend exposes two APIs.
There is a full API that sensuctl uses ( port 8080 by default)
And there is an agent API that sensu-agent uses (port 8081 by default)

Is the agent api a subset of the control api? or does it have additional endpoints that need to be documented?

**Comment by apaskulin** [comment]
@jspaleta The agent API is its own thing, documented here https://docs.sensu.io/sensu-go/5.0/reference/agent/#using-the-http-socket
