### ISSUE TITLE
Sensu 2.0 Epic: Guides

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#722]
This is a tracking ticket for all planned docs within the Guides section.

### Existing Guides

- [x] Monitoring Server Resources #737
- [x] Monitoring External Resources #758
- [x] Sending Slack Alerts #757 
- [ ] Reducing Alert Fatigue
- [ ] Running Auto-Remediation #847
- [ ] Planning Maintenance
- [ ] Creating a Read Only User
- [ ] Using Assets in Checks
- [ ] Check Output Metric Extraction
- [ ] Scheduling Checks
- [ ] Aggregating Metrics with StatsD
- [ ] Storing Metrics with InfluxDB

### New Guides

- [x] Running a Sensu Cluster #671
- [ ] Monitoring Kubernetes with Sensu #851
- [ ] Collecting Prometheus Metrics #850
- [ ] Scaling Sensu #848
- [ ] Securing Sensu #849
- [ ] Troubleshooting #837
- [ ] Monitoring Sensu with Sensu #846

### Stretch Goals

- Auto-Remediation with a Handler

---

### Securing Sensu

- etcd port for peer communication (SSL)
- REST API http (sensuctl) SSL
- Agent API ws

**Comment by apaskulin** [comment]
This work is now being tracked in individual issues.
